language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chirag96/docker-devops-test -f Dockerfile.dev .

script:
  - docker run -e CI=true chirag96/docker-devops-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-app"
  env: "DockerApp-env"
  bucket_name: "elasticbeanstalk-eu-west-1-287114609732"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
